### ISSUE TITLE
I got this error while installing the requirements.

### ISSUE THREAD

**Issue by Tropical-Smootie** [N0rz3/Inspector#1]
<img width="1429" alt="Screenshot 2023-05-17 at 5 59 12 PM" src="https://github.com/N0rz3/Inspector/assets/67304179/1cd4d87e-7875-4913-9ffb-6fd6d16bc32f">

**Comment by N0rz3** [comment]
hello then for this error I do not know at all there are several solutions either:
- python is badly installed
- you typed the command wrong but at first glance I don't see any mistakes
- you typed the command in the wrong place
check that you are in the Inspector folder with the README, license and core

if not try to search for the code of your error on google
